# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
